// src/components/Chart.jsx
import React from 'react';
import './chart.css'
import atmospherics from './../utils/atmospherics';

const Chart = ({firearm, rangeData, round, targetData, weatherData, onExportChart, onPrintChart}) => {
    const { name: firearmName, reticleUnits, turretUnits } = firearm;
    const { name: roundName } = round;
    const { distanceUnits, slantDegrees, speedMPH } = targetData;
    const { altitudeFeet, windVelocityMPH, windAngleDegrees } = weatherData;

    const showMil = turretUnits==='Mil' || reticleUnits==='Mil';
    const showMoA = turretUnits==='MoA' || reticleUnits==='MoA';
    const showIPHY = turretUnits==='IPHY' || reticleUnits==='IPHY';
    const speedOfSound = atmospherics.speedOfSound(altitudeFeet);
    return (
        <div className="bal-chart">
            <div className="card" id="chart">
                <div className="card-heading">
                    <span>Range Chart - Firearm ({firearmName}) - Round ({roundName})</span>
                    <div className='card-heading-spacer'></div>
                    <button className='btn btn-secondary card-heading-button' onClick={onExportChart}> Export</button>
                    <button className='btn btn-secondary card-heading-button' onClick={onPrintChart}> Print</button>
                </div>
                <div className="card-body">
                    <div className="table-responsive">
                        <table id="ballisticsTable" className="table table-condensed table-striped table-hover font-size-small">
                            <thead>
                                <tr>
                                    <th data-toggle="tooltip" title="Range in yards from the muzzle to the bullet">
                                        Range<br/>{distanceUnits==='Yards' ? '(yards)': '(meters)'}
                                    </th>
                                    <th data-toggle="tooltip" title="Velocity of the bullet in feet per second">
                                        Velocity<br/>(FPS)
                                    </th>
                                    <th className="d-none d-sm-table-cell" data-toggle="tooltip" title="Energy of the bullet on impact">
                                        Energy<br/>(FtLbs)
                                    </th>
                                    <th className="d-none d-sm-table-cell" data-toggle="tooltip" title="Time the bullet has been in flight since leaving the muzzle">
                                        Time<br/>(sec)
                                    </th>
                                    <th className="d-none d-sm-table-cell" data-toggle="tooltip" title="Amount of bullet drop in relation to the muzzle angle not the ground">
                                        Drop<br/>(inch)
                                    </th>
                                    <th className='d-none d-md-table-cell' data-toggle="tooltip" title="Bullet elevation above or below the target centerline">
                                        Elevation<br/>(inch)
                                    </th>
                                    {showMil ? 
                                        <th data-toggle="tooltip" title="Bullet elevation above or below the target centerline">
                                            Elevation<br/>(Mil)
                                        </th>
                                        : null
                                    }
                                    {showMoA ? 
                                        <th data-toggle="tooltip" title="Bullet elevation above or below the target centerline">
                                            Elevation<br/>(MoA)
                                        </th>
                                        : null
                                    }
                                    {showIPHY ? 
                                        <th data-toggle="tooltip" title="Bullet elevation above or below the target centerline">
                                            Elevation<br/>(IPHY)
                                        </th>
                                        : null
                                    }
                                    <th className='d-none d-md-table-cell' data-toggle="tooltip" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
                                        Wind<br/>
                                        {windVelocityMPH} MPH<br/>
                                        {windAngleDegrees} deg<br/>
                                        (inch)
                                    </th>
                                    {showMil ? 
                                        <th data-toggle="tooltip" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
                                            Wind<br/>
                                            {windVelocityMPH} MPH<br/>
                                            {windAngleDegrees} deg<br/>
                                            (Mil)
                                        </th>
                                        : null
                                    }
                                    {showMoA ? 
                                        <th data-toggle="tooltip" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
                                            Wind<br/>
                                            {windVelocityMPH} MPH<br/>
                                            {windAngleDegrees} deg<br/>
                                            (MoA)
                                        </th>
                                        : null
                                    }
                                    {showIPHY ? 
                                        <th data-toggle="tooltip" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
                                            Wind<br/>
                                            {windVelocityMPH} MPH<br/>
                                            {windAngleDegrees} deg<br/>
                                            (IPHY)
                                        </th>
                                        : null
                                    }
                                    <th className='d-none d-md-table-cell' data-toggle="tooltip" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
                                        Lead<br/>
                                        {speedMPH} MPH<br/>
                                        (inch)
                                    </th>
                                    {showMil ? 
                                        <th data-toggle="tooltip" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
                                            Lead<br/>
                                            {speedMPH} MPH<br/>
                                            (Mil)
                                        </th>
                                        : null
                                    }
                                    {showMoA ? 
                                        <th data-toggle="tooltip" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
                                            Lead<br/>
                                            {speedMPH} MPH<br/>
                                            (MoA)
                                        </th>
                                        : null
                                    }
                                    {showIPHY ? 
                                        <th data-toggle="tooltip" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
                                            Lead<br/>
                                            {speedMPH} MPH<br/>
                                            (IPHY)
                                        </th>
                                        : null
                                    }
                                    <th className='d-none d-md-table-cell' data-toggle="tooltip" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
                                        Slant<br/>
                                        {slantDegrees} deg<br/>
                                        (inch)
                                    </th>
                                    {showMil ? 
                                        <th data-toggle="tooltip" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
                                            Slant<br/>
                                            {slantDegrees} deg<br/>
                                            (Mil)
                                        </th>
                                        : null
                                    }
                                    {showMoA ? 
                                        <th data-toggle="tooltip" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
                                            Slant<br/>
                                            {slantDegrees} deg<br/>
                                            (MoA)
                                        </th>
                                        : null
                                    }
                                    {showIPHY ? 
                                        <th data-toggle="tooltip" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
                                            Slant<br/>
                                            {slantDegrees} deg<br/>
                                            (IPHY)
                                        </th>
                                        : null
                                    }
                                </tr>
                            </thead>
                            <tbody className='table-group-divider'>
                                {rangeData.map((rangeData, index) => {
                                    const { rangeMeters, rangeYards, velocityFPS, energyFtLbs, timeSeconds, dropInches, verticalPositionInches, crossWindDriftInches, leadInches, verticalPositionMil, verticalPositionMoA, verticalPositionIPHY, crossWindDriftMil, crossWindDriftMoA, crossWindDriftIPHY, leadMil, leadMoA, leadIPHY, slantDropInches, slantMil, slantMoA, slantIPHY } = rangeData;
                                    return (
                                        <tr key={index} className={velocityFPS<=speedOfSound ? 'text-danger' : velocityFPS<=speedOfSound*1.2 && velocityFPS>speedOfSound ? 'text-warning' : null}>
                                            <td>{distanceUnits==='Yards' ? rangeYards : rangeMeters}</td>
                                            <td>{velocityFPS.toFixed(0)}</td>
                                            <td className="d-none d-sm-table-cell">{energyFtLbs.toFixed(0)}</td>
                                            <td className="d-none d-sm-table-cell">{timeSeconds.toFixed(3)}</td>
                                            <td className="d-none d-sm-table-cell">{-dropInches.toFixed(1)}</td>
                                            <td className='d-none d-md-table-cell'>{-verticalPositionInches.toFixed(1)}</td>
                                            {showMil ?
                                                <td>{-verticalPositionMil.toFixed(1)}</td>
                                                : null
                                            }
                                            {showMoA ?
                                                <td>{-verticalPositionMoA.toFixed(1)}</td>
                                                : null
                                            }
                                            {showIPHY ?
                                                <td>{-verticalPositionIPHY.toFixed(1)}</td>
                                                : null
                                            }
                                            <td className='d-none d-md-table-cell'>{crossWindDriftInches.toFixed(1)}</td>
                                            {showMil ?
                                                <td>{crossWindDriftMil.toFixed(1)}</td>
                                                : null
                                            }
                                            {showMoA ?
                                                <td>{crossWindDriftMoA.toFixed(1)}</td>
                                                : null
                                            }
                                            {showIPHY ?
                                                <td>{crossWindDriftIPHY.toFixed(1)}</td>
                                                : null
                                            }
                                            <td className='d-none d-md-table-cell'>{leadInches.toFixed(1)}</td>
                                            {showMil ?
                                                <td>{leadMil.toFixed(1)}</td>
                                                : null
                                            }
                                            {showMoA ?
                                                <td>{leadMoA.toFixed(1)}</td>
                                                : null
                                            }
                                            {showIPHY ?
                                                <td>{leadIPHY.toFixed(1)}</td>
                                                : null
                                            }
                                            <td className='d-none d-md-table-cell'>{slantDropInches.toFixed(1)}</td>
                                            {showMil ?
                                                <td>{slantMil.toFixed(1)}</td>
                                                : null
                                            }
                                            {showMoA ?
                                                <td>{slantMoA.toFixed(1)}</td>
                                                : null
                                            }
                                            {showIPHY ?
                                                <td>{slantIPHY.toFixed(1)}</td>
                                                : null
                                            }
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div className="card-footer card-footer-text d-flex p-2 justify-content-around">
                    <span className="chart-legend-warning">Orange text denotes transsonic flight</span>
                    <span className="chart-legend-danger">Red text denotes subsonic flight</span>
                </div>
            </div>
        </div>
    );
}

export default Chart;

// src/app/components/chart/chart.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/forkJoin';

import { TARGET, WEATHER } from '../../data/conditions.data'

import { Firearm } from '../../models/firearm.model'
import { Range } from '../../models/range.model'
import { Round } from '../../models/round.model'
import { Target } from '../../models/target.model'
import { Weather } from '../../models/weather.model'

import { AtmosphericService } from '../../services/atmospheric.service'
import { ConversionService } from '../../services/conversion.service'
import { DataService } from '../../services/data.service'
import { DragService } from '../../services/drag.service'

@Component({
     moduleId: module.id.toString(),
     selector: 'chart',
     styleUrls: ['chart.component.css'],
     templateUrl: 'chart.component.html'
})
export class ChartComponent implements OnInit {

	showMil: boolean = true;
	showMoA: boolean = true;
	showIPHY: boolean = true;
	rangeData: Array<any>;

	public _isOpen: boolean = true;
    @Input()
    set isOpen(isOpen: boolean) {
        this._isOpen = isOpen;
    }

    constructor(private _atmosphericService: AtmosphericService, private _conversionService: ConversionService, public dataService: DataService, private _dragService: DragService) {}

    ngOnInit() {
		//Assumes this component is not loaded until after we have a dataService with currentFirearm, currentRound, currentTarget, and currentWeather
		this.showMil = this.dataService.currentFirearm.turretUnits==0 || this.dataService.currentFirearm.reticleUnits==0;
		this.showMoA = this.dataService.currentFirearm.turretUnits==1 || this.dataService.currentFirearm.reticleUnits==1;
		this.showIPHY = this.dataService.currentFirearm.turretUnits==3 || this.dataService.currentFirearm.reticleUnits==3;
		this.rangeData = this.getRangeData();
		while(this.rangeData.length < 6) {
			//Reduce the stepping to ensure we have a good sample of data between muzzle and subsonic
			this.dataService.currentTarget.chartStepping = Math.floor(this.dataService.currentTarget.chartStepping / 2);
			this.rangeData = this.getRangeData();
		}
		if(this.rangeData.length > 20) {
			//Reset chart stepping back to the default value to prevent excessive run times and long graphs
			this.dataService.currentTarget.chartStepping = 50;
			this.rangeData = this.getRangeData();
		}
	}

	back() {
		console.log('back() not implemented');
	};

	graphBar() {
		console.log('graphBar() not implemented');
	};

	graphLine() {
		console.log('graphLine() not implemented');
	};

    getDistanceYards(actualTargetSizeInches: number, reticleViewedTargetSizeMils: number) {
        return Math.round((actualTargetSizeInches/36) * 1000 / reticleViewedTargetSizeMils);
    }

	getRangeData(): Array<Range> {
		////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		// What other calculations exist in drag.js that are not yet on the chart?
		//		clicksToReachMaximumPointBlankRangeZero
		//		maxPointBlankRangeZeroYards
		//		maximumPointBlankRange
		//		optimalRiflingTwist
		//		rifleRecoilVelocity
		//		rifleRecoilEnergy
		//		sectionalDensity
		// What about making all the calculators available?
		//		getDistanceYards
		//		degreesToRadians
		//		inchesToIPHY
		//		inchesToMil
		//		inchesToMinutesOfAngle
		//		milesPerHourToInchesPerSecond
		//		radiansToDegrees
		//		secant
		//		speedOfSound (at different altitudes)
		//		weightDensityOfAir (at different altitudes)
		//		standardRelativeHumidity (at different altitudes)
		////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Loop through from Range = 0 to the maximum range and display the ballistics table at each chart stepping range.
        var currentBallisticCoefficient = this._dragService.modifiedBallisticCoefficient(this.dataService.currentRound.bulletBC, this.dataService.currentWeather.altitudeFeet, this.dataService.currentWeather.temperatureDegreesFahrenheit, this.dataService.currentWeather.barometericPressureInchesHg, this.dataService.currentWeather.relativeHumidityPercent);
        var muzzleAngleDegrees = this._dragService.muzzleAngleDegreesForZeroRange(this.dataService.currentRound.muzzleVelocityFPS, this.dataService.currentFirearm.zeroRangeYards, this.dataService.currentFirearm.sightHeightInches, currentBallisticCoefficient);
        var currentCrossWindDriftInches, currentDropInches, currentEnergyFtLbs, currentLeadInches, currentTimeSeconds, currentVelocityFPS, currentVerticalPositionInches;
        //Skip the first row
        var currentRangeYards = this.dataService.currentTarget.chartStepping;
		var rangeData: Array<Range> = [];
        while ((currentVelocityFPS == null) || (currentVelocityFPS > this._atmosphericService.speedOfSoundAtSeaLevel)) {
			currentVelocityFPS = this._dragService.velocityFromRange(currentBallisticCoefficient, this.dataService.currentRound.muzzleVelocityFPS, currentRangeYards);
			currentEnergyFtLbs = this._dragService.energy(this.dataService.currentRound.bulletWeightGrains, currentVelocityFPS);
			currentTimeSeconds = this._dragService.time(currentBallisticCoefficient, this.dataService.currentRound.muzzleVelocityFPS, currentVelocityFPS);
			currentDropInches = this._dragService.drop(this.dataService.currentRound.muzzleVelocityFPS, currentVelocityFPS, currentTimeSeconds);
			currentVerticalPositionInches = this._dragService.verticalPosition(this.dataService.currentFirearm.sightHeightInches, muzzleAngleDegrees, currentRangeYards, currentDropInches);
			//Cross Winds take on full range value regardless of Slant To Target
			currentCrossWindDriftInches = this._dragService.crossWindDrift(currentRangeYards, currentTimeSeconds, this.dataService.currentWeather.windAngleDegrees, this.dataService.currentWeather.windVelocityMPH, muzzleAngleDegrees, this.dataService.currentRound.muzzleVelocityFPS);
			currentLeadInches = this._dragService.lead(this.dataService.currentTarget.speedMPH, currentTimeSeconds);
			let slantDropInches: number = currentDropInches * (1-Math.cos(this._conversionService.degreesToRadians(this.dataService.currentTarget.slantDegrees)));
			let range: Range = {
				rangeYards: currentRangeYards,
				velocityFPS: currentVelocityFPS,
				energyFtLbs: currentEnergyFtLbs,
				timeSeconds: currentTimeSeconds,
				dropInches: currentDropInches,
				verticalPositionInches: -currentVerticalPositionInches,  //Go negative to reflect how much scope dial up is needed
				crossWindDriftInches: currentCrossWindDriftInches,
				leadInches: currentLeadInches,
				slantDegrees: this.dataService.currentTarget.slantDegrees,
				// //Al the remaining properties are computed
				verticalPositionMil: this._conversionService.inchesToMil(-currentVerticalPositionInches, currentRangeYards),
				verticalPositionMoA: this._conversionService.inchesToMinutesOfAngle(-currentVerticalPositionInches, currentRangeYards),
				verticalPositionIPHY: this._conversionService.inchesToIPHY(-currentVerticalPositionInches, currentRangeYards),
				crossWindDriftMil: this._conversionService.inchesToMil(currentCrossWindDriftInches, currentRangeYards),
				crossWindDriftMoA: this._conversionService.inchesToMinutesOfAngle(currentCrossWindDriftInches, currentRangeYards),
				crossWindDriftIPHY: this._conversionService.inchesToIPHY(currentCrossWindDriftInches, currentRangeYards),
				leadMil: this._conversionService.inchesToMil(currentLeadInches, currentRangeYards),
				leadMoA: this._conversionService.inchesToMinutesOfAngle(currentLeadInches, currentRangeYards),
				leadIPHY: this._conversionService.inchesToIPHY(currentLeadInches, currentRangeYards),
				slantDropInches: slantDropInches,
				slantMil: this._conversionService.inchesToMil(slantDropInches, currentRangeYards),
				slantMoA: this._conversionService.inchesToMinutesOfAngle(slantDropInches, currentRangeYards),
				slantIPHY: this._conversionService.inchesToIPHY(slantDropInches, currentRangeYards)
			};
			rangeData.push(range);
			currentRangeYards += this.dataService.currentTarget.chartStepping;
        }
		return rangeData;
	};
}
<div class="panel panel-primary">
	<div class="panel-heading">
		<div class="panel-title">Range Chart - Firearm ({{firearm.name}}) - Round ({{round.name}}>)</div>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-condensed table-striped table-hover font-size-small">
				<thead>
					<tr>
						<th data-bind="tooltip: {trigger: 'hover click'}" title="Range in yards from the muzzle to the bullet">
							Range<br>(yards)
						</th>
						<th data-bind="tooltip: {trigger: 'hover click'}" title="Velocity of the bullet in feet per second">
							Velocity<br>(FPS)
						</th>
						<th class="hidden-xs" data-bind="tooltip: {trigger: 'hover click'}" title="Energy of the bullet on impact">
							Energy<br>(FtLbs)
						</th>
						<th class="hidden-xs" data-bind="tooltip: {trigger: 'hover click'}" title="Time the bullet has been in flight since leaving the muzzle">
							Time<br>(sec)
						</th>
						<th class="hidden-xs" data-bind="tooltip: {trigger: 'hover click'}" title="Amount of bullet drop in relation to the muzzle angle not the ground">
							Drop<br>(inch)
						</th>
						<th class='visible-md visible-lg' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet elevation above or below the target centerline">
							Elevation<br>(inch)
						</th>
						<th *ngIf='showMil' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet elevation above or below the target centerline">
							Elevation<br>(Mil)
						</th>
						<th *ngIf='showMoa' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet elevation above or below the target centerline">
							Elevation<br>(MoA)
						</th>
						<th *ngIf='showIPHY' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet elevation above or below the target centerline">
							Elevation<br>(IPHY)
						</th>
						<th class='visible-md visible-lg' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
							Wind<br>
							{{dataService.currentWeather.windVelocityMPH}} MPH<br>
							{{dataService.currentWeather.windAngleDegrees}} deg<br>
							(inch)
						</th>
						<th *ngIf='showMil' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
							Wind<br>
							{{dataService.currentWeather.windVelocityMPH}} MPH<br>
							{{dataService.currentWeather.windAngleDegrees}} deg<br>
							(Mil)
						</th>
						<th *ngIf='showMoa' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
							Wind<br>
							{{dataService.currentWeather.windVelocityMPH}} MPH<br>
							{{dataService.currentWeather.windAngleDegrees}} deg<br>
							(MoA)
						</th>
						<th *ngIf='showIPHY' data-bind="tooltip: {trigger: 'hover click'}" title="Bullet drift left or right of the target centerline.  Drift is calculated at 90 degrees with velocity automatically adjusted from original wind direction.">
							Wind<br>
							{{dataService.currentWeather.windVelocityMPH}} MPH<br>
							{{dataService.currentWeather.windAngleDegrees}} deg<br>
							(IPHY)
						</th>
						<th class='visible-md visible-lg' data-bind="tooltip: {trigger: 'hover click'}" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
							Lead<br>
							{{dataService.currentTarget.speedMPH}} MPH<br>
							(inch)
						</th>
						<th *ngIf='showMil' data-bind="tooltip: {trigger: 'hover click'}" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
							Lead<br>
							{{dataService.currentTarget.speedMPH}} MPH<br>
							(Mil)
						</th>
						<th *ngIf='showMoa' data-bind="tooltip: {trigger: 'hover click'}" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
							Lead<br>
							{{dataService.currentTarget.speedMPH}} MPH<br>
							(MoA)
						</th>
						<th *ngIf='showIPHY' data-bind="tooltip: {trigger: 'hover click'}" title="Amount of distance a moving target will cover during the time it takes for the bullet to travel from the muzzle to the target.">
							Lead<br>
							{{dataService.currentTarget.speedMPH}} MPH<br>
							(IPHY)
						</th>
						<th class='visible-md visible-lg' data-bind="tooltip: {trigger: 'hover click'}" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
							Slant<br>
							{{dataService.currentTarget.slantDegrees}} deg<br>
							(inch)
						</th>
						<th  *ngIf='showMil' data-bind="tooltip: {trigger: 'hover click'}" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
							Slant<br>
							{{dataService.currentTarget.slantDegrees}} deg<br>
							(Mil)
						</th>
						<th *ngIf='showMoa' data-bind="tooltip: {trigger: 'hover click'}" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
							Slant<br>
							{{dataService.currentTarget.slantDegrees}} deg<br>
							(MoA)
						</th>
						<th *ngIf='showIPHY' data-bind="tooltip: {trigger: 'hover click'}" title="Amount you will need to hold low on a target that is of either a higher or lower elevation than the shooting position.  Always aim low for both up and down slants.">
							Slant<br>
							{{dataService.currentTarget.slantDegrees}} deg<br>
							(IPHY)
						</th>
					</tr>
				</thead>
				<tbody>
					<tr *ngFor='let rangeRow of rangeData'>
						<td>{{rangeRow.rangeYards}}</td>
						<td>{{rangeRow.velocityFPS.toFixed(0)}}</td>
						<td class="hidden-xs">{{rangeRow.energyFtLbs.toFixed(0)}}</td>
						<td class="hidden-xs">{{rangeRow.timeSeconds.toFixed(3)}}</td>
						<td class="hidden-xs">{{rangeRow.dropInches.toFixed(1)}}</td>
						<td class='visible-md visible-lg'>{{rangeRow.verticalPositionInches.toFixed(1)}}</td>
						<td *ngIf='showMil'>{{rangeRow.verticalPositionMil().toFixed(1)}}</td>
						<td *ngIf='showMoa'>{{rangeRow.verticalPositionMoA().toFixed(1)}}</td>
						<td *ngIf='showIPHY'>{{rangeRow.verticalPositionIPHY().toFixed(1)}}</td>
						<td class='visible-md visible-lg'>{{rangeRow.crossWindDriftInches.toFixed(1)}}</td>
						<td *ngIf='showMil'>{{rangeRow.crossWindDriftMil().toFixed(1)}}</td>
						<td *ngIf='showMoa'>{{rangeRow.crossWindDriftMoA().toFixed(1)}}</td>
						<td *ngIf='showIPHY'>{{rangeRow.crossWindDriftIPHY().toFixed(1)}}</td>
						<td class='visible-md visible-lg'>{{rangeRow.leadInches.toFixed(1)}}</td>
						<td *ngIf='showMil'>{{rangeRow.leadMil().toFixed(1)}}</td>
						<td *ngIf='showMoa'>{{rangeRow.leadMoA().toFixed(1)}}</td>
						<td *ngIf='showIPHY'>{{rangeRow.leadIPHY().toFixed(1)}}</td>
						<td class='visible-md visible-lg'>{{rangeRow.slantDropInches().toFixed(1)}}</td>
						<td *ngIf='showMil'>{{rangeRow.slantMil().toFixed(1)}}</td>
						<td *ngIf='showMoa'>{{rangeRow.slantMoA().toFixed(1)}}</td>
						<td *ngIf='showIPHY'>{{rangeRow.slantIPHY().toFixed(1)}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="panel-footer">
		<button class="btn btn-default" (click)='back();'><span class="fa fa-chevron-left"></span> Back</button>
		<button class="btn btn-default" (click)='graphBar();'><span class="fa fa-chevron-right"></span> Graph (Bar)</button>
		<button class="btn btn-default" (click)='graphLine();'><span class="fa fa-chevron-right"></span> Graph (Line)</button>
	</div>
</div>
