// src/components/Firearms.jsx
import React, { useState } from 'react';
import './form.css'

const Firearms = ({firearms, onAdd, onSelect}) => {
    return (
        <div className="bal-form">
            <div className="card">
                <div className="card-heading d-flex p-2">
                    Select Firearm
                </div>
                <div className={`card-body`}>
                    <ul className="list-inline">
                        {firearms.map((firearm) => (
                            <li onClick={() => onSelect(firearm)} className='card' key={firearm.id}>
                                <div className="well">
                                    {firearm.name}
                                </div>
                            </li>
                        ))}
                    </ul>
                </div>
                <div className={`card-footer`}>
                    <button className="btn btn-default" onClick={() => onAdd()}><span className="fa fa-plus"></span> Add Firearm</button>&nbsp;
                </div>
            </div>
        </div>
    );
}

export default Firearms;

// src/app/ballistics-module/components/firearms/firearms.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { Firearm } from '../../models/firearm.model';

@Component({
	selector: 'firearms',
	styleUrls: ['./firearms.component.css'],
	templateUrl: './firearms.component.html'
})
export class FirearmsComponent {

	public currentFirearm: Firearm = null;

	public _firearms: Array<Firearm> = null;
	@Input()
	set firearms(firearms: Array<Firearm>) {
		if (firearms) {
			this._firearms = firearms;
		} else {
			this.firearms = [];
		}
	}

	@Output() onAdd = new EventEmitter();
	@Output() onSelect = new EventEmitter<Firearm>();

	add() {
		this.onAdd.emit();
	}

	select(firearm: Firearm) {
		this.currentFirearm = firearm;
		this.onSelect.emit(this.currentFirearm);
	}

}

<div *ngIf='_firearms' class="card">
    <div class="card-heading bg-dark text-light clearfix p-2">
		Select Firearm
	</div>
	<div class="card-body">
		<ul class="list-inline">
			<li *ngFor='let firearm of _firearms' (click)='select(firearm);' class='card'>
				<div class="well" [class.active]='currentFirearm===firearm'>
					{{ firearm.name }}
				</div>
			</li>
		</ul>
	</div>
	<div class="card-footer">
		<button class="btn btn-lg btn-default" (click)='add();'><span class="fa fa-plus"></span> Add Firearm</button>
	</div>
</div>
