// src/app/components/round/round.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { Round } from '../../models/round.model'

@Component({
     moduleId: module.id.toString(),
     selector: 'round',
     styleUrls: ['round.component.css'],
     templateUrl: 'round.component.html'
})
export class RoundComponent {

    public editedRound: Round = null;
    public isViewOnly: boolean = true;

    public _isOpen: boolean = true;
    @Input()
    set isOpen(isOpen: boolean) {
        this._isOpen = isOpen;
    }

    private _firearmName:string = '';
    @Input()
    set firearmName(name: string) {
        if (name) {
            this._firearmName = name;
        }
    }

    _round: Round = null;
    @Input()
    set round(round: Round) {
        if (round) {
            this._round = round;
            let editedRound = {
                id: round.id,
                firearmId: round.firearmId,
                name: round.name,
                bulletBC: round.bulletBC,
                bulletDiameterInches: round.bulletDiameterInches,
                bulletWeightGrains: round.bulletWeightGrains,
                muzzleVelocityFPS: round.muzzleVelocityFPS
            }
            this.editedRound = editedRound;
        }
    }

    // Bubble up that the form was saved
    @Output() onSave = new EventEmitter<Round>();

    edit() {
        this.isViewOnly = false;
    }

    save(): void {
        this.onSave.emit(this.editedRound);
        this.isViewOnly = true;
    }

    cancel(): void {
        // Reset the form back to the original object
        this.round = this._round;
        this.isViewOnly = true;
    }

}

<div *ngIf='editedRound' class="panel panel-primary">
	<div class="panel-heading clearfix" data-toggle="collapse" (click)='_isOpen=!_isOpen'>
		<div class="panel-title pull-left">Firearm ({{ _firearmName }}) - Round ({{ editedRound.name }})</div>
		<i class="fa fa-fw pull-right" [class.fa-chevron-up]='!_isOpen' [class.fa-chevron-down]='_isOpen'></i>
	</div>
	<div class="panel-collapse collapse" [class.in]="_isOpen">
		<div class="panel-body">
			<form #form="ngForm" novalidate>
				<div class="form-group" [class.has-error]="nameControl.invalid && nameControl.dirty">
						<label class="control-label">Name</label>
						<div class="input-group margin-bottom-sm">
							<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
							<input type="text" name="name" [(ngModel)]="editedRound.name" #nameControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Name" required autofocus minlength="3"  maxlength="50">
						</div>
						<div [hidden]="isViewOnly || nameControl.valid || nameControl.pristine" class="alert alert-danger">
							Name is required and must be between 3 and 50 characters
						</div>
					</div>
				<div class="form-group" [class.has-error]="bulletDiameterInchesControl.invalid && bulletDiameterInchesControl.dirty">
					<label class="control-label" title="Bullet diameter is required so wind resistance can be calculated properly">Bullet Diameter (inches)</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<input type="number" name="bulletDiameterInches" [(ngModel)]="editedRound.bulletDiameterInches" #bulletDiameterInchesControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Bullet Diameter (inches)" required autofocus min="0.010" max="1">
					</div>
					<div [hidden]="isViewOnly || bulletDiameterInchesControl.valid || bulletDiameterInchesControl.pristine" class="alert alert-danger">
						Bullet diameter is required so wind resistance can be calculated.  Common diameters are 0.022 to 0.050 inches
					</div>
				</div>
				<div class="form-group" [class.has-error]="bulletWeightGrainsControl.invalid && bulletWeightGrainsControl.dirty">
					<label class="control-label" title="Bullet weight is required, so inertia can be calculated properly">Bullet Weight (grains)</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<input type="number" name="bulletWeightGrains" [(ngModel)]="editedRound.bulletWeightGrains" #bulletWeightGrainsControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Bullet Weight (grains)" required min="10" max="1000">
					</div>
					<div [hidden]="isViewOnly || bulletWeightGrainsControl.valid || bulletWeightGrainsControl.pristine" class="alert alert-danger">
						Bullet weight is required, so bullet drop can be calculated properly
					</div>
				</div>
				<div class="form-group" [class.has-error]="muzzleVelocityFPSControl.invalid && muzzleVelocityFPSControl.dirty">
					<label class="control-label" title="Muzzle velocity is required, so bullet deceleration can be calculated properly">Muzzle Velocity (FPS)</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<input type="number" name="muzzleVelocityFPS" [(ngModel)]="editedRound.muzzleVelocityFPS" #muzzleVelocityFPSControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Muzzle Velocity (FPS)" required min="100" max="5000">
					</div>
					<div [hidden]="isViewOnly || muzzleVelocityFPSControl.valid || muzzleVelocityFPSControl.pristine" class="alert alert-danger">
						Muzzle velocity is required, so bullet drop can be calculated properly
					</div>
				</div>
				<div class="form-group" [class.has-error]="bulletBCControl.invalid && bulletBCControl.dirty">
					<label class="control-label" title="Bullet ballistic cooefficient is the aerodynamics of the bullet's ability to resist atmospheric density related deceleration">Bullet Ballistic Cooefficient</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<input type="number" name="bulletBC" [(ngModel)]="editedRound.bulletBC" #bulletBCControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Bullet Ballistic Cooefficient" required min="0.010" max="1">
					</div>
					<div [hidden]="isViewOnly || bulletBCControl.valid || bulletBCControl.pristine" class="alert alert-danger">
						Bullet ballistic cooefficient is required, so wind resistance can be calculated properly
					</div>
				</div>
			</form>
		</div>
		<div class="panel-footer">
			<div *ngIf='isViewOnly'>
				<button type="submit" class="btn btn-success" (click)='edit()'><i class="fa fa-check"></i> Edit</button>
			</div>
			<div *ngIf='!isViewOnly'>
				<button type="submit" class="btn btn-success" [disabled]="form.pristine || form.invalid" (click)='save()'><i class="fa fa-check"></i> Save</button>
				<button type="submit" class="btn btn-danger" (click)="cancel()"><i class="fa fa-times"></i> Cancel</button>
			</div>
		</div>
	</div>
</div>

// src/components/Round.jsx
import React from 'react';
import { useForm } from "react-hook-form";
import './form.css'

const Round = ({round, onClose, onDelete, onSubmit}) => {
    const { id, name, bulletBC, bulletDiameterInches, bulletWeightGrains, muzzleVelocityFPS } = round;
    const { register, handleSubmit, formState: { errors } } = useForm({ mode: 'onBlur' });
    if(!round) {
        return null;
    }
    return (
        <div className="bal-form">
            <div className="card">
                <div className="card-heading d-flex p-2">
                    { id==='Add' ? `Add Round` : `Round - ${name}`}
                </div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={`card-body`}>
                        <input hidden name="id" defaultValue={id} type="text" {...register("id")}/>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="name"
                                data-toggle="tooltip"
                                title="Name used to identify this round unique to the firearm."
                            >
                                Name
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-text-o fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={name}
                                    maxLength="50"
                                    minLength="3"
                                    name="name"
                                    placeholder="Name"
                                    {...register("name", {
                                        maxLength: { value: 50, message: "Name has a maximum length of 50" },
                                        minLength: { value: 3, message: "Name has a minimum length of 3" },
                                        required: "Name is required"
                                    })}
                                    required
                                    type="text"
                                />
                            </div>
                            {errors.name && errors.name.message ?
                                <div className="alert alert-danger">
                                    {errors.name.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="bulletDiameterInches"
                                data-toggle="tooltip"
                                title="Bullet diameter is required so wind resistance can be calculated properly.  Common diameters are 0.022 to 0.050 inches."
                            >
                                Bullet Diameter (inches)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-superpowers fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={bulletDiameterInches}
                                    max="1"
                                    min="0.010"
                                    name="bulletDiameterInches"
                                    placeholder="Bullet Diameter (inches)"
                                    {...register("bulletDiameterInches", {
                                        max: { value: 1, message: "Bullet Diameter has a maximum value of 1" },
                                        min: { value: 0.010, message: "Bullet Diameter has a minimum value of 0.010" },
                                        required: "Bullet diameter is required so wind resistance can be calculated."
                                    })}
                                    required
                                    step="0.001"
                                    type="number"
                                />
                            </div>
                            {errors.bulletDiameterInches && errors.bulletDiameterInches.message ?
                                <div className="alert alert-danger">
                                    {errors.bulletDiameterInches.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="bulletWeightGrains"
                                data-toggle="tooltip"
                                title="Bullet weight is required, so inertia can be calculated properly."
                            >
                                Bullet Weight (grains)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-balance-scale fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={bulletWeightGrains}
                                    max="1000"
                                    min="10"
                                    name="bulletWeightGrains"
                                    placeholder="Bullet Weight (grains)"
                                    {...register("bulletWeightGrains", {
                                        max: { value: 1000, message: "Bullet Weight has a maximum value of 1000" },
                                        min: { value: 10, message: "Bullet Weight has a minimum value of 10" },
                                        required: "Bullet Weight is required, so bullet drop can be calculated properly."
                                    })}
                                    required
                                    step="1"
                                    type="number"
                                />
                            </div>
                            {errors.bulletWeightGrains && errors.bulletWeightGrains.message ?
                                <div className="alert alert-danger">
                                    {errors.bulletWeightGrains.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="muzzleVelocityFPS"
                                data-toggle="tooltip"
                                title="Muzzle velocity is required, so bullet deceleration can be calculated properly."
                            >
                                Muzzle Velocity (FPS)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-signal fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={muzzleVelocityFPS}
                                    max="5000"
                                    min="100"
                                    name="muzzleVelocityFPS"
                                    placeholder="Muzzle Velocity (FPS)"
                                    {...register("muzzleVelocityFPS", {
                                        max: { value: 5000, message: "Muzzle Velocity has a maximum value of 5000" },
                                        min: { value: 100, message: "Muzzle Velocity has a minimum value of 100" },
                                        required: "Muzzle Velocity is required, so bullet drop can be calculated properly."
                                    })}
                                    required
                                    step="1"
                                    type="number"
                                />
                            </div>
                            {errors.muzzleVelocityFPS && errors.muzzleVelocityFPS.message ?
                                <div className="alert alert-danger">
                                    {errors.muzzleVelocityFPS.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="bulletBC"
                                data-toggle="tooltip"
                                title="Bullet ballistic cooefficient is the aerodynamics of the bullet's ability to resist atmospheric density related deceleration."
                            >
                                Bullet Ballistic Cooefficient
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-google-wallet fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={bulletBC}
                                    max="1"
                                    min="0.010"
                                    name="bulletBC"
                                    placeholder="Bullet Ballistic Cooefficient"
                                    {...register("bulletBC", {
                                        max: { value: 1, message: "Bullet ballistic cooefficient has a maximum value of 1" },
                                        min: { value: 0.010, message: "Bullet ballistic cooefficient has a minimum value of 0.010" },
                                        required: "Bullet ballistic cooefficient is required, so wind resistance can be calculated properly."
                                    })}
                                    required
                                    step="0.001"
                                    type="number"
                                />
                            </div>
                            {errors.bulletBC && errors.bulletBC.message ?
                                <div className="alert alert-danger">
                                    {errors.bulletBC.message}
                                </div>
                                : null
                            }
                        </div>
                    </div>
                    <div className={`card-footer`}>
                        <button className="btn btn-success" type="submit"><span className="fa fa-check"></span> Save</button>&nbsp;
                        <button className="btn btn-warning" onClick={() => onClose()}> Close</button>&nbsp;
                        <button className="btn btn-danger" onClick={() => onDelete(round)}> Delete</button>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default Round;
