// src/components/Firearm.jsx
import React from 'react';
import { useForm } from "react-hook-form";
import './form.css'

const Firearm = ({firearm, onClose, onSubmit, onDelete}) => {
    const { register, handleSubmit, formState: { errors } } = useForm({ mode: 'onBlur' });
    if(!firearm) {
        return null;
    }
    return (
        <div className="bal-form">
            <div className="card">
                <div className="card-heading d-flex p-2">
                    { firearm.id==='Add' ? `Add Firearm` : `Firearm - ${firearm.name}`}
                </div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={`card-body`}>
                        <input hidden name="id" defaultValue={firearm.id} type="text" {...register("id")}/>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="name"
                                data-toggle="tooltip"
                                title="Name used to uniquely identify this firearm."
                            >
                                Name
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-file-o fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={firearm.name}
                                    maxLength="50"
                                    minLength="3"
                                    name="name"
                                    placeholder="Name"
                                    {...register("name", {
                                        maxLength: { value: 50, message: "Name has a maximum length of 50" },
                                        minLength: { value: 3, message: "Name has a minimum length of 3" },
                                        required: "Name is required"
                                    })}
                                    required
                                    type="text"
                                />
                            </div>
                            {errors.name && errors.name.message ?
                                <div className="alert alert-danger">
                                    {errors.name.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="sightHeightInches"
                                data-toggle="tooltip"
                                title="Measured form bore centerline to scope centerline. Common heights are 1.5 to 2 inches."
                            >
                                Sight Height (inches)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-crosshairs fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={firearm.sightHeightInches}
                                    max="5"
                                    min="0.25"
                                    name="sightHeightInches"
                                    placeholder="Sight Height (inches)"
                                    {...register("sightHeightInches", {
                                        max: { value: 5, message: "Sight Height has a maximum value of 5" },
                                        min: { value: 0.25, message: "Sight Height has a minimum value of 0.25" },
                                        required: "Sight Height is required"
                                    })}
                                    required
                                    step="0.0005"
                                    type="number"
                                />
                            </div>
                            {errors.sightHeightInches && errors.sightHeightInches.message ?
                                <div className="alert alert-danger">
                                    {errors.sightHeightInches.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="zeroRange"
                                data-toggle="tooltip"
                                title="Range at which scope has been adjusted for point of aim = point of impact."
                            >
                                Zero Range
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-circle-o fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={firearm.zeroRange}
                                    max="3000"
                                    min="10"
                                    name="zeroRange"
                                    placeholder="Zero Range"
                                    {...register("zeroRange", {
                                        max: { value: 3000, message: "Zero Range has a maximum value of 3000" },
                                        min: { value: 10, message: "Zero Range has a minimum value of 10" },
                                        required: "Zero Range is required, so bullet drop can be calculated properly"
                                    })}
                                    required
                                    type="number"
                                />
                                <select
                                    className="form-control"
                                    defaultValue={firearm.zeroRangeUnits}
                                    name="zeroRangeUnits"
                                    {...register("zeroRangeUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Yards'>Yards</option>
                                    <option value='Meters'>Meters</option>
                                </select>
                            </div>
                            {errors.zeroRange && errors.zeroRange.message ?
                                <div className="alert alert-danger">
                                    {errors.zeroRange.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="reticleUnits"
                                data-toggle="tooltip"
                                title="Scope crosshair hash mark separation.  Usually Minutes of Angle (MoA), Milliradian (Mil), or Inch Per Hundred Yards (IPHY)."
                            >
                                Reticle Units
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-spinner fa-fw"></i></span>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.reticleUnits}
                                    name="reticleUnits"
                                    {...register("reticleUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Mil'>Mil</option>
                                    <option value='MoA'>MoA</option>
                                    <option value='IPHY'>IPHY</option>
                                </select>
                            </div>
                            {errors.reticleUnits && errors.reticleUnits.message ?
                                <div className="alert alert-danger">
                                    {errors.reticleUnits.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="elevationTurretGradients"
                                data-toggle="tooltip"
                                title="Number of elevation (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)."
                            >
                                Elevation Turret (clicks per unit)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-align-center fa-fw"></i></span>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.elevationTurretGradients}
                                    name="elevationTurretGradients"
                                    {...register("elevationTurretGradients", {
                                        required: true
                                    })}
                                >
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                    <option value='10'>10</option>
                                </select>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.turretUnits}
                                    name="turretUnits"
                                    {...register("turretUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Mil'>Mil</option>
                                    <option value='MoA'>MoA</option>
                                    <option value='IPHY'>IPHY</option>
                                </select>
                            </div>
                            {errors.elevationTurretGradients && errors.elevationTurretGradients.message ?
                                <div className="alert alert-danger">
                                    {errors.elevationTurretGradients.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="windageTurretGradients"
                                data-toggle="tooltip"
                                title="Number of windage (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)."
                            >
                                Windage Turret (clicks per unit)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-repeat fa-fw"></i></span>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.windageTurretGradients}
                                    name="windageTurretGradients"
                                    {...register("windageTurretGradients", {
                                        required: true
                                    })}
                                >
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                    <option value='10'>10</option>
                                </select>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.turretUnits}
                                    name="turretUnits"
                                    {...register("turretUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Mil'>Mil</option>
                                    <option value='MoA'>MoA</option>
                                    <option value='IPHY'>IPHY</option>
                                </select>
                            </div>
                            {errors.windageTurretGradients && errors.windageTurretGradients.message ?
                                <div className="alert alert-danger">
                                    {errors.windageTurretGradients.message}
                                </div>
                                : null
                            }
                        </div>
                    </div>
                    <div className={`card-footer`}>
                        <button className="btn btn-success" type="submit"><span className="fa fa-check"></span> Save</button>&nbsp;
                        <button className="btn btn-warning" onClick={() => onClose()}> Close</button>&nbsp;
                        <button className="btn btn-danger" onClick={() => onDelete(firearm)}> Delete</button>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default Firearm;

// src/app/ballistics-module/components/firearm/firearm.component.ts
import { Component, OnInit } from '@angular/core';

import { ToastrService } from 'ngx-toastr';

import { Firearm } from '../../models/firearm.model';
import { LengthEnum } from '../../models/length-enum.model';
import { Status } from '../../models/status.model';

import { DataService } from '../../services/data.service';

@Component({
	selector: 'app-firearm',
	styleUrls: ['./firearm.component.css'],
	templateUrl: './firearm.component.html'
})
export class FirearmComponent implements OnInit {

	firearms: Firearm[] = null;
	firearm: Firearm = {
        id: null,
        name: null,
        elevationTurretGradients: null,
        reticleUnits: null,
        rounds: [],
        sightHeightInches: null,
        turretUnits: null,
        windageTurretGradients: null,
        zeroRangeUnits: LengthEnum.Yards,
        zeroRange: null
    };
	isOpen = true;
    status: Status = null;
    get statusEnum() { return Status; }

    constructor(private dataService: DataService, private toastrService: ToastrService) { }

	ngOnInit(): void {
		this.dataService.getFirearms().subscribe(firearms => {
            this.firearms = firearms;
        });
		this.dataService.getFirearmId().subscribe(firearmId => {
            if(this.firearms != null && firearmId != null) {
                this.firearm = this.firearms.find(f => f.id===firearmId);
            }
        });
		this.dataService.getStatus().subscribe(status => {
            this.status = status;
        });
	}

	close(): void {
		this.dataService.selectFirearm(null);
		this.dataService.updateStatus(Status.SelectFirearm);
	}

	delete(): void {
		this.dataService.deleteFirearm(this.firearm.id);
        this.toastrService.success('Deleted','Firearm Status');
        this.close();
	}

	save(): void {
        if(this.status===Status.AddFirearm) {
		    this.dataService.insertFirearm(this.firearm);
        } else {
		    this.dataService.updateFirearm(this.firearm);
        }
		this.dataService.updateStatus(Status.SelectRound);
        this.toastrService.success('Saved','Firearm Status');
	}

}

<div *ngIf='editedFirearm' class="card">
    <div class="card-heading bg-dark text-light d-flex p-2">
		<span *ngIf="_mode==='add'">Add Firearm</span>
		<span *ngIf="_mode==='edit'">Firearm - {{ editedFirearm.name }}</span>
		<i class="fa fa-fw ml-auto" [class.fa-chevron-right]="!isOpen" [class.fa-chevron-down]="isOpen" (click)="isOpen=!isOpen"></i>
	</div>
	<div class="card-body" [class.collapse]="!isOpen">
		<form #form="ngForm" novalidate (change)='change(form.valid);'>
			<div class="form-group" [class.has-error]="nameControl.invalid && nameControl.dirty">
				<label class="control-label">Name</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-file-o fa-fw"></i></div></div>
					<input type="text" name="name" [(ngModel)]="editedFirearm.name" #nameControl="ngModel" [disabled]="_mode==='view'" class="form-control" placeholder="Name" required minlength="3"  maxlength="50">
				</div>
				<div [hidden]="_mode==='view' || nameControl.valid || nameControl.pristine" class="alert alert-danger">
					Name is required and must be between 3 and 50 characters
				</div>
			</div>
			<div class="form-group" [class.has-error]="sightHeightInchesControl.invalid && sightHeightInchesControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Measured form bore centerline to scope centerline">Sight Height (inches)</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-crosshairs fa-fw"></i></div></div>
					<input type="number" name="sightHeightInches" [(ngModel)]="editedFirearm.sightHeightInches" #sightHeightInchesControl="ngModel" class="form-control" placeholder="Sight Height (inches)" required min="0" max="20">
				</div>
				<div [hidden]="_mode==='view' || sightHeightInchesControl.valid || sightHeightInchesControl.pristine" class="alert alert-danger">
					Sight height is required.  Common heights are 1.5 to 2 inches
				</div>
			</div>
			<div class="form-group" [class.has-error]="zeroRangeYardsControl.invalid && zeroRangeYardsControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Range at which scope has been adjusted for point of aim = point of impact">Zero Range (yards)</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-circle-o fa-fw"></i></div></div>
					<input type="number" name="zeroRangeYards" [(ngModel)]="editedFirearm.zeroRangeYards" #zeroRangeYardsControl="ngModel" class="form-control" placeholder="Zero Range (yards)" required min="25" max="3000" >
				</div>
				<div [hidden]="_mode==='view' || zeroRangeYardsControl.valid || zeroRangeYardsControl.pristine" class="alert alert-danger">
					Zero range is required, so bullet drop can be calculated properly
				</div>
			</div>
			<div class="form-group" [class.has-error]="reticleUnitsControl.invalid && reticleUnitsControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Scope crosshair hash mark separation.  Usually Minutes of Angle (MoA), Milliradian (Mil), or Inch Per Hundred Yards (IPHY)">Reticle Units</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-spinner fa-fw"></i></div></div>
					<select name="reticleUnits" [(ngModel)]="editedFirearm.reticleUnits" #reticleUnitsControl="ngModel" class="form-control" required>
						<option [ngValue]='0'>Mil</option>
						<option [ngValue]='1'>MoA</option>
						<option [ngValue]='2'>IPHY</option>
					</select>
				</div>
				<div [hidden]="_mode==='view' || reticleUnitsControl.valid || reticleUnitsControl.pristine" class="alert alert-danger">
						Reticle units are required rangeing and hold overs
				</div>
			</div>
			<div class="form-group" [class.has-error]="turretUnitsControl.invalid && turretUnitsControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Scope turret hash mark separation.  Usually Minutes of Angle (MoA), Milliradian (Mil), or Inch Per Hundred Yards (IPHY)">Turret Units</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-circle-thin fa-fw"></i></div></div>
					<select name="turretUnits" [(ngModel)]="editedFirearm.turretUnits" #turretUnitsControl="ngModel" class="form-control" required>
						<option [ngValue]='0'>Mil</option>
						<option [ngValue]='1'>MoA</option>
						<option [ngValue]='2'>IPHY</option>
					</select>
				</div>
				<div [hidden]="_mode==='view' || turretUnitsControl.valid || turretUnitsControl.pristine" class="alert alert-danger">
						Turret units are required for rangeing and hold overs
				</div>
			</div>
			<div class="form-group" [class.has-error]="elevationTurretGradientsControl.invalid && elevationTurretGradientsControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Number of elevation (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)">Elevation Turret Gradients</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-align-center fa-fw"></i></div></div>
					<select name="elevationTurretGradients" [(ngModel)]="editedFirearm.elevationTurretGradients" #elevationTurretGradientsControl="ngModel" class="form-control" required>
						<option *ngIf='editedFirearm.turretUnits!=0' [ngValue]='1'>1</option>
						<option *ngIf='editedFirearm.turretUnits!=0' [ngValue]='2'>2</option>
						<option *ngIf='editedFirearm.turretUnits!=0' [ngValue]='4'>4</option>
						<option *ngIf='editedFirearm.turretUnits==0' [ngValue]='10'>10</option>
					</select>
				</div>
				<div [hidden]="_mode==='view' || elevationTurretGradientsControl.valid || elevationTurretGradientsControl.pristine" class="alert alert-danger">
						Elevation turret gradients allows values 1,2,4 or 10 (# clicks per turret unti 1,2,4 for MoA and IPHY, and 10 for Mil)
				</div>
			</div>
			<div class="form-group" [class.has-error]="windageTurretGradientsControl.invalid && windageTurretGradientsControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Number of windage (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)">Windage Turret Gradients</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-repeat fa-fw"></i></div></div>
					<select name="windageTurretGradients" [(ngModel)]="editedFirearm.windageTurretGradients" #windageTurretGradientsControl="ngModel" class="form-control" required>
						<option *ngIf='editedFirearm.turretUnits!=0' [ngValue]='1'>1</option>
						<option *ngIf='editedFirearm.turretUnits!=0' [ngValue]='2'>2</option>
						<option *ngIf='editedFirearm.turretUnits!=0' [ngValue]='4'>4</option>
						<option *ngIf='editedFirearm.turretUnits==0' [ngValue]='10'>10</option>
					</select>
				</div>
				<div [hidden]="_mode==='view' || windageTurretGradientsControl.valid || windageTurretGradientsControl.pristine" class="alert alert-danger">
						Windage turret gradients allows values 1,2,4 or 10 (# clicks per turret unti 1,2,4 for MoA and IPHY, and 10 for Mil)
				</div>
			</div>
		</form>
	</div>
	<div class="card-footer" [class.collapse]="!isOpen">
		<div *ngIf="_mode==='add'">
			<button type="submit" class="btn btn-success" [disabled]="form.pristine || form.invalid" (click)='save()'><i class="fa fa-check"></i> Save</button>&nbsp;
			<button class='btn btn-danger' (click)='close();'> Cancel</button>
		</div>
		<div *ngIf="_mode=='edit'">
			<button type="submit" class="btn btn-success" [disabled]="form.pristine || form.invalid" (click)='save()'><i class="fa fa-check"></i> Save</button>&nbsp;
			<button *ngIf='isPristine' class='btn btn-warning' (click)='close();'> Close</button>&nbsp;
			<button *ngIf='isPristine' class='btn btn-danger' mwlConfirmationPopover [popoverTitle]="'Confirm Delete'" [popoverMessage]="'Delete this firearm?'" placement="top" (confirm)="delete()"> Delete</button>
			<button *ngIf='!isPristine' class='btn btn-warning' (click)='cancel();'> Cancel</button>
		</div>
	</div>
</div>
