// src/components/Target.jsx
import React, { useState } from 'react';
import { useForm } from "react-hook-form";
import './form.css'

import conversions from './../utils/conversions';

const Target = ({targetData, onSubmit}) => {
    const {distanceUnits, distance, chartStepping, sizeInches, sizeMils, slantDegrees, speedMPH} = targetData;
    const { register, getValues, handleSubmit, setValue, formState: { errors } } = useForm({ mode: 'onBlur' });
    const setDistance = () => {
        const values = getValues();
        // Given the size of a target in both inches and mils, will calculate and update the distance
        if(values.sizeInches !== '' && values.sizeMils !== '') {
            const distanceYards = conversions.sizeToDistance(values.sizeInches, values.sizeMils);
            const distance = Math.round(values.distanceUnits==="Yards" ? distanceYards : conversions.yardsToMeters(distanceYards));
            setValue('distance', distance);
        }
    }
    return (
        <div className="bal-form">
            <div className="card">
                <div className="card-heading d-flex p-2">
                    Target
                </div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={`card-body`}>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="distance"
                                data-toggle="tooltip"
                                title="Distance measured from the muzzle to the target."
                            >
                                Distance
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-bullseye fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={distance}
                                    max="5000"
                                    min="0"
                                    onBlur={() => setValue('sizeMils', '')}
                                    placeholder="Distance"
                                    {...register("distance", {
                                        max: { value: 5000, message: "Distance has a maximum value of 5000" },
                                        min: { value: 0, message: "Distance has a minimum value of 0" },
                                        required: "Distance is required to determine how far out to calculate ballistics data"
                                    })}
                                    required
                                    type="number"
                                />
                                <select
                                    className="form-control"
                                    defaultValue={distanceUnits}
                                    {...register("distanceUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Yards'>Yards</option>
                                    <option value='Meters'>Meters</option>
                                </select>
                            </div>
                            {errors.distance && errors.distance.message ?
                                <div className="alert alert-danger">
                                    {errors.distance.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="sizeInches"
                                data-toggle="tooltip"
                                title="The size of the target in inches (optional).  Used in combination with the size of the target in Mils to determine the distance."
                            >
                                Size (Inches / Mils) - optional
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-ellipsis-v fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={sizeInches}
                                    max="120"
                                    min="1"
                                    placeholder="Size (inches)"
                                    onBlur={async () => setDistance()}
                                    {...register("sizeInches", {
                                        max: { value: 120, message: "Size (inches) has a maximum value of 120" },
                                        min: { value: 1, message: "Size (inches) has a minimum value of 1" },
                                    })}
                                    type="number"
                                />
                                <input
                                    className="form-control"
                                    defaultValue={sizeMils}
                                    max="100"
                                    min="0.1"
                                    onBlur={() => setDistance()}
                                    placeholder="Size (mils)"
                                    {...register("sizeMils", {
                                        max: { value: 100, message: "Size (mils) has a maximum value of 100" },
                                        min: { value: 0.1, message: "Size (mils) has a minimum value of 0.1" },
                                    })}
                                    step="0.1"
                                    type="number"
                                />
                            </div>
                            {errors.sizeInches && errors.sizeInches.message ?
                                <div className="alert alert-danger">
                                    {errors.sizeInches.message}
                                </div>
                                : null
                            }
                            {errors.sizeMils && errors.sizeMils.message ?
                                <div className="alert alert-danger">
                                    {errors.sizeMils.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="chartStepping"
                                data-toggle="tooltip"
                                title="Chart stepping is required to determine how many rows to calculate."
                            >
                                Chart Stepping (yards)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-bars fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={chartStepping}
                                    max="500"
                                    min="1"
                                    placeholder="Chart Stepping (yards)"
                                    {...register("chartStepping", {
                                        max: { value: 500, message: "Chart Stepping has a maximum value of 500" },
                                        min: { value: 1, message: "Chart Stepping has a minimum value of 1" },
                                        required: "Chart Stepping is required to determine how many rows to calculate"
                                    })}
                                    required
                                    type="number"
                                />
                            </div>
                            {errors.chartStepping && errors.chartStepping.message ?
                                <div className="alert alert-danger">
                                    {errors.chartStepping.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="slantDegrees"
                                data-toggle="tooltip"
                                title="The angle versus horizontal as measured between the muzzle and target.  Slant degrees is required to determine vertical hold over or angle scope adjustments needed.  Both up and down slant angles result in the need to aim low."
                            >
                                Slant (degrees)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-location-arrow fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={slantDegrees}
                                    max="500"
                                    min="10"
                                    placeholder="Slant (degrees)"
                                    {...register("slantDegrees", {
                                        max: { value: 500, message: "Slant has a maximum value of 500" },
                                        min: { value: 10, message: "Slant has a minimum value of 10" },
                                        required: "Slant is required to determine vertical hold over or angle scope adjustments needed.  Both up and down slant angles result in the need to aim low."
                                    })}
                                    required
                                    type="number"
                                />
                            </div>
                            {errors.slantDegrees && errors.slantDegrees.message ?
                                <div className="alert alert-danger">
                                    {errors.slantDegrees.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="speedMPH"
                                data-toggle="tooltip"
                                title="The speed the target is moving perpendicular to the line between the muzzle and target.  Target speed is required to determine horizontal lead hold or scope adjustments needed."
                            >
                                Speed (MPH)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-car fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={speedMPH}
                                    max="500"
                                    min="1"
                                    placeholder="Speed (MPH)"
                                    {...register("speedMPH", {
                                        max: { value: 500, message: "Speed has a maximum value of 500" },
                                        min: { value: 1, message: "Speed has a minimum value of 1" },
                                        required: "Target speed is required to determine horizontal lead hold or scope adjustments needed."
                                    })}
                                    required
                                    type="number"
                                />
                            </div>
                            {errors.speedMPH && errors.speedMPH.message ?
                                <div className="alert alert-danger">
                                    {errors.speedMPH.message}
                                </div>
                                : null
                            }
                        </div>
                    </div>
                    <div className={`card-footer`}>
                        <button className="btn btn-success" type="submit"><span className="fa fa-check"></span> Save</button>&nbsp;
                    </div>
                </form>
            </div>
        </div>
    );
}

export default Target;

// src/app/ballistics-module/components/target/target.component.ts
import { Component, OnInit } from '@angular/core';

import { DataService } from '../../services/data.service';
import conversions from 'pg-conversions';

import { Target } from '../../models/target.model';

@Component({
	selector: 'app-target',
	styleUrls: ['./target.component.css'],
	templateUrl: './target.component.html'
})
export class TargetComponent implements OnInit {

	isOpen = true;
    target: Target = null;
    targetSizeMils: number = null;

	constructor(private dataService: DataService) {}

	ngOnInit(): void {
		this.dataService.getTarget().subscribe(target => {
            this.target = target;
        });
	}

	change(isValid: boolean): void {
		if(isValid) {
            this.dataService.updateTarget(this.target);
		}
	}

    getDistance(): void {
        // Given the size of a target in both inches and mils, will calculate and update the distance
        if(this.target != null && this.target.sizeInches != null && this.targetSizeMils != null) {
            const distanceYards = conversions.sizeToDistance(this.target.sizeInches, this.targetSizeMils);
            this.target.distance = this.target.distanceUnits==='Yards' ? distanceYards : conversions.yardsToMeters(distanceYards);
        }
    }

}

<div *ngIf='target != null' class="card">
    <div class="card-heading bg-dark text-light d-flex p-2">
        Target
		<i class="fa fa-fw ml-auto" [class.fa-chevron-right]="!isOpen" [class.fa-chevron-down]="isOpen" (click)="isOpen=!isOpen"></i>
    </div>
	<div class="card-body" [class.collapse]="!isOpen">
		<form #form="ngForm" novalidate (change)='change(form.valid);'>
			<div class="form-group" [class.has-error]="distanceControl.invalid && distanceControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Distance measured from the muzzle to the target">Distance</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-bullseye fa-fw"></i></div></div>
					<input type="number" name="distance" [(ngModel)]="target.distance" #distanceControl="ngModel" class="form-control" placeholder="Distance" required min="0" max="5000" step="5" (change)="targetSizeMils=null">
                    <select name="distanceUnits" [(ngModel)]="target.distanceUnits" #distanceUnitsControl="ngModel" class="form-control" required>
                        <option>Yards</option>
                        <option>Meters</option>
                    </select>
				</div>
				<div [hidden]="distanceControl.valid || distanceControl.pristine" class="alert alert-danger">
					Distance is required to determine how far out to calculate ballistics data
				</div>
			</div>
            {{target.distanceUnits}}
			<div class="form-group" [class.has-error]="sizeInchesControl.invalid && sizeInchesControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="The size of the target in inches (optional).  Used in combination with the size of the target in Mils to determine the distance.">Size (Inches / Mils) - optional</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-ellipsis-v fa-fw"></i></div></div>
					<input type="number" name="sizeInches" [(ngModel)]="target.sizeInches" #sizeInchesControl="ngModel" class="form-control" placeholder="Inches" min="1" max="120" (change)="this.getDistance()">
					<input type="number" name="targetSizeMils" [(ngModel)]="targetSizeMils" #targetSizeMilsControl="ngModel" class="form-control" placeholder="" min="0.1" max="100" step='0.1' (change)="this.getDistance()">
				</div>
				<div [hidden]="sizeInchesControl.valid || sizeInchesControl.pristine" class="alert alert-danger">
					Target size should be between 1 and 120 inches.
				</div>
				<div [hidden]="targetSizeMilsControl.valid || targetSizeMilsControl.pristine" class="alert alert-danger">
					Target Mils should be between 1 and 100.
				</div>
			</div>
			<div class="form-group" [class.has-error]="chartSteppingControl.invalid && chartSteppingControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="Chart stepping is required to determine how many rows to calculate">Chart Stepping (yards)</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-bars fa-fw"></i></div></div>
					<input type="number" name="chartStepping" [(ngModel)]="target.chartStepping" #chartSteppingControl="ngModel" class="form-control" placeholder="Chart Stepping (yards)" required min="10" max="500">
				</div>
				<div [hidden]="chartSteppingControl.valid || chartSteppingControl.pristine" class="alert alert-danger">
					Chart stepping is required to determine how many rows to calculate
				</div>
			</div>
			<div class="form-group" [class.has-error]="slantDegreesControl.invalid && slantDegreesControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="The angle versus horizontal as measured between the muzzle and target.  Slant degrees is required to determine vertical hold over or angle scope adjustments needed.  Both up and down slant angles result in the need to aim low.">Slant (degrees)</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-location-arrow fa-fw"></i></div></div>
					<input type="number" name="slantDegrees" [(ngModel)]="target.slantDegrees" #slantDegreesControl="ngModel" class="form-control" placeholder="Slant (degrees)" required min="10" max="500">
				</div>
				<div [hidden]="slantDegreesControl.valid || slantDegreesControl.pristine" class="alert alert-danger">
					Slant degrees is required to determine vertical hold over or angle scope adjustments needed.  Both up and down slant angles result in the need to aim low.
				</div>
			</div>
			<div class="form-group" [class.has-error]="speedMPHControl.invalid && speedMPHControl.dirty">
				<label class="control-label" data-toggle="tooltip" title="The speed the target is moving perpendicular to the line between the muzzle and target.  Target speed is required to determine horizontal lead hold or scope adjustments needed.">Speed (MPH)</label>
				<div class="input-group margin-bottom-sm">
	                <div class="input-group-prepend"><div class="input-group-text"><i class="fa fa-car fa-fw"></i></div></div>
					<input type="number" name="speedMPH" [(ngModel)]="target.speedMPH" #speedMPHControl="ngModel" class="form-control" placeholder="Speed (MPH)" required min="1" max="500">
				</div>
				<div [hidden]="speedMPHControl.valid || speedMPHControl.pristine" class="alert alert-danger">
					Target speed is required to determine horizontal lead hold or scope adjustments needed.
				</div>
			</div>
		</form>
	</div>
</div>
