// src/components/Rounds.jsx
import React from 'react';
import './form.css'

const Rounds = ({rounds, onAdd, onSelect}) => {
    if(!rounds) {
        return null;
    }
    return (
        <div className="bal-form">
            <div className="card">
                <div className="card-heading d-flex p-2">
                    Select Round
                </div>
                <div className={`card-body`}>
                    <ul className="list-inline">
                        {rounds.map((round) => (
                            <li onClick={() => onSelect(round)} className='card' key={round.id}>
                                <div className="well">
                                    {round.name}
                                </div>
                            </li>
                        ))}
                    </ul>
                </div>
                <div className={`card-footer`}>
                    <button className="btn btn-default" onClick={() => onAdd()}><span className="fa fa-plus"></span> Add Round</button>&nbsp;
                </div>
            </div>
        </div>
    );
}

export default Rounds;

// src/app/ballistics-module/components/rounds/rounds.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { Round } from '../../models/round.model';

@Component({
		selector: 'app-rounds',
		styleUrls: ['./rounds.component.css'],
		templateUrl: './rounds.component.html'
})
export class RoundsComponent {

	public currentRound: Round = null;
	public isOpen = true;

	public _rounds: Array<Round> = [];
	@Input()
	set rounds(rounds: Array<Round>) {
		if (rounds) {
			this._rounds = rounds;
		} else {
			this._rounds = [];
		}
	}

	@Output() onAdd = new EventEmitter();
	@Output() onSelect = new EventEmitter<Round>();

	add() {
		this.onAdd.emit();
	}

	select(round: Round) {
		this.currentRound = round;
		this.onSelect.emit(this.currentRound);
	}

}

<div *ngIf='_rounds && _isOpen' class="panel panel-primary">
	<div class="panel-heading clearfix" data-toggle="collapse" (click)='_isOpen=!_isOpen'>
		<div class="panel-title pull-left">Select Round</div>
		<i class="fa fa-fw pull-right" [class.fa-chevron-up]='!_isOpen' [class.fa-chevron-down]='_isOpen'></i>
	</div>
	<div class="panel-collapse collapse" [class.in]="_isOpen">
			<div class="panel-body">
			<ul class="list-inline">
				<li *ngFor='let round of _rounds' (click)='select(round);' class='card' >
					<div class="well" [class.active]='currentRound===round'>
						<p class="lead">{{ round.name }}</p>
					</div>
				</li>
			</ul>
		</div>
		<div class="panel-footer">
			<button class="btn btn-default" (click)='addRound();'><span class="fa fa-plus"></span> Add Round</button>
		</div>
	</div>
</div>
