// src/components/Firearm.jsx
import React from 'react';
import { useForm } from "react-hook-form";
import './form.css'

const Firearm = ({firearm, onClose, onSubmit, onDelete}) => {
    const { register, handleSubmit, formState: { errors } } = useForm({ mode: 'onBlur' });
    if(!firearm) {
        return null;
    }
    return (
        <div className="bal-form">
            <div className="card">
                <div className="card-heading d-flex p-2">
                    { firearm.id==='Add' ? `Add Firearm` : `Firearm - ${firearm.name}`}
                </div>
                <form onSubmit={handleSubmit(onSubmit)}>
                    <div className={`card-body`}>
                        <input hidden name="id" defaultValue={firearm.id} type="text" {...register("id")}/>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="name"
                                data-toggle="tooltip"
                                title="Name used to uniquely identify this firearm."
                            >
                                Name
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-file-o fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={firearm.name}
                                    maxLength="50"
                                    minLength="3"
                                    name="name"
                                    placeholder="Name"
                                    {...register("name", {
                                        maxLength: { value: 50, message: "Name has a maximum length of 50" },
                                        minLength: { value: 3, message: "Name has a minimum length of 3" },
                                        required: "Name is required"
                                    })}
                                    required
                                    type="text"
                                />
                            </div>
                            {errors.name && errors.name.message ?
                                <div className="alert alert-danger">
                                    {errors.name.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="sightHeightInches"
                                data-toggle="tooltip"
                                title="Measured form bore centerline to scope centerline. Common heights are 1.5 to 2 inches."
                            >
                                Sight Height (inches)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-crosshairs fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={firearm.sightHeightInches}
                                    max="5"
                                    min="0.25"
                                    name="sightHeightInches"
                                    placeholder="Sight Height (inches)"
                                    {...register("sightHeightInches", {
                                        max: { value: 5, message: "Sight Height has a maximum value of 5" },
                                        min: { value: 0.25, message: "Sight Height has a minimum value of 0.25" },
                                        required: "Sight Height is required"
                                    })}
                                    required
                                    step="0.0005"
                                    type="number"
                                />
                            </div>
                            {errors.sightHeightInches && errors.sightHeightInches.message ?
                                <div className="alert alert-danger">
                                    {errors.sightHeightInches.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="zeroRange"
                                data-toggle="tooltip"
                                title="Range at which scope has been adjusted for point of aim = point of impact."
                            >
                                Zero Range
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-circle-o fa-fw"></i></span>
                                <input
                                    className="form-control"
                                    defaultValue={firearm.zeroRange}
                                    max="3000"
                                    min="10"
                                    name="zeroRange"
                                    placeholder="Zero Range"
                                    {...register("zeroRange", {
                                        max: { value: 3000, message: "Zero Range has a maximum value of 3000" },
                                        min: { value: 10, message: "Zero Range has a minimum value of 10" },
                                        required: "Zero Range is required, so bullet drop can be calculated properly"
                                    })}
                                    required
                                    type="number"
                                />
                                <select
                                    className="form-control"
                                    defaultValue={firearm.zeroRangeUnits}
                                    name="zeroRangeUnits"
                                    {...register("zeroRangeUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Yards'>Yards</option>
                                    <option value='Meters'>Meters</option>
                                </select>
                            </div>
                            {errors.zeroRange && errors.zeroRange.message ?
                                <div className="alert alert-danger">
                                    {errors.zeroRange.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="reticleUnits"
                                data-toggle="tooltip"
                                title="Scope crosshair hash mark separation.  Usually Minutes of Angle (MoA), Milliradian (Mil), or Inch Per Hundred Yards (IPHY)."
                            >
                                Reticle Units
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-spinner fa-fw"></i></span>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.reticleUnits}
                                    name="reticleUnits"
                                    {...register("reticleUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Mil'>Mil</option>
                                    <option value='MoA'>MoA</option>
                                    <option value='IPHY'>IPHY</option>
                                </select>
                            </div>
                            {errors.reticleUnits && errors.reticleUnits.message ?
                                <div className="alert alert-danger">
                                    {errors.reticleUnits.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="elevationTurretGradients"
                                data-toggle="tooltip"
                                title="Number of elevation (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)."
                            >
                                Elevation Turret (clicks per unit)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-align-center fa-fw"></i></span>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.elevationTurretGradients}
                                    name="elevationTurretGradients"
                                    {...register("elevationTurretGradients", {
                                        required: true
                                    })}
                                >
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                    <option value='10'>10</option>
                                </select>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.turretUnits}
                                    name="turretUnits"
                                    {...register("turretUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Mil'>Mil</option>
                                    <option value='MoA'>MoA</option>
                                    <option value='IPHY'>IPHY</option>
                                </select>
                            </div>
                            {errors.elevationTurretGradients && errors.elevationTurretGradients.message ?
                                <div className="alert alert-danger">
                                    {errors.elevationTurretGradients.message}
                                </div>
                                : null
                            }
                        </div>
                        <div className="form-group">
                            <label
                                className="control-label"
                                htmlFor="windageTurretGradients"
                                data-toggle="tooltip"
                                title="Number of windage (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)."
                            >
                                Windage Turret (clicks per unit)
                            </label>
                            <div className="input-group margin-bottom-sm">
                                <span className="input-group-text"><i className="fa fa-repeat fa-fw"></i></span>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.windageTurretGradients}
                                    name="windageTurretGradients"
                                    {...register("windageTurretGradients", {
                                        required: true
                                    })}
                                >
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                    <option value='10'>10</option>
                                </select>
                                <select
                                    className="form-control"
                                    defaultValue={firearm.turretUnits}
                                    name="turretUnits"
                                    {...register("turretUnits", {
                                        required: true
                                    })}
                                >
                                    <option value='Mil'>Mil</option>
                                    <option value='MoA'>MoA</option>
                                    <option value='IPHY'>IPHY</option>
                                </select>
                            </div>
                            {errors.windageTurretGradients && errors.windageTurretGradients.message ?
                                <div className="alert alert-danger">
                                    {errors.windageTurretGradients.message}
                                </div>
                                : null
                            }
                        </div>
                    </div>
                    <div className={`card-footer`}>
                        <button className="btn btn-success" type="submit"><span className="fa fa-check"></span> Save</button>&nbsp;
                        <button className="btn btn-warning" onClick={() => onClose()}> Close</button>&nbsp;
                        <button className="btn btn-danger" onClick={() => onDelete(firearm)}> Delete</button>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default Firearm;

// src/app/components/firearm/firearm.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { Firearm } from '../../models/firearm.model'

@Component({
     moduleId: module.id.toString(),
     selector: 'firearm',
     styleUrls: ['firearm.component.css'],
     templateUrl: 'firearm.component.html'
})
export class FirearmComponent {

    public editedFirearm: Firearm = null;
    public isViewOnly: boolean = true;

    public _isOpen: boolean = true;
    @Input()
    set isOpen(isOpen: boolean) {
        this._isOpen = isOpen;
    }

    _firearm: Firearm = null;
    @Input()
    set firearm(firearm: Firearm) {
        if (firearm) {
            this._firearm = firearm;
            let editedFirearm = {
                id: firearm.id,
                userId: firearm.userId,
                name: firearm.name,
                elevationTurretGradients: firearm.elevationTurretGradients,
                reticleUnits: firearm.reticleUnits,
                rounds: firearm.rounds,
                sightHeightInches: firearm.sightHeightInches,
                turretUnits: firearm.turretUnits,
                windageTurretGradients:firearm.windageTurretGradients,
                zeroRangeYards: firearm.zeroRangeYards,
            }
            this.editedFirearm = editedFirearm;
        }
    }

    @Output() onChange = new EventEmitter();
    @Output() onSave = new EventEmitter<Firearm>();

    change() {
        this.isOpen = false;
        this.onChange.emit();
    }

    edit() {
        this.isViewOnly = false;
    }

    save(): void {
        this.onSave.emit(this.editedFirearm);
        this.isViewOnly = true;
    }

    cancel(): void {
        // Reset the form back to the original object
        this.firearm = this._firearm;
        this.isViewOnly = true;
    }
}
<div *ngIf='editedFirearm' class="panel panel-primary">
	<div class="panel-heading clearfix" data-toggle="collapse" (click)='_isOpen=!_isOpen'>
		<div class="panel-title pull-left">Firearm ({{ editedFirearm.name }})</div>
		<i class="fa fa-fw pull-right" [class.fa-chevron-up]='!_isOpen' [class.fa-chevron-down]='_isOpen'></i>
	</div>
	<div class="panel-collapse collapse" [class.in]="_isOpen">
		<div class="panel-body">
			<form #form="ngForm" novalidate>
					<div class="form-group" [class.has-error]="nameControl.invalid && nameControl.dirty">
						<label class="control-label">Name</label>
						<div class="input-group margin-bottom-sm">
							<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
							<input type="text" name="name" [(ngModel)]="editedFirearm.name" #nameControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Name" required autofocus minlength="3"  maxlength="50">
						</div>
						<div [hidden]="isViewOnly || nameControl.valid || nameControl.pristine" class="alert alert-danger">
							Name is required and must be between 3 and 50 characters
						</div>
					</div>
					<div class="form-group" [class.has-error]="sightHeightInchesControl.invalid && sightHeightInchesControl.dirty">
					<label class="control-label" title="Measured form bore centerline to scope centerline">Sight Height (inches)</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<input type="number" name="sightHeightInches" [(ngModel)]="editedFirearm.sightHeightInches" #sightHeightInchesControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Sight Height (inches)" required min="0" max="20">
					</div>
					<div [hidden]="isViewOnly || sightHeightInchesControl.valid || sightHeightInchesControl.pristine" class="alert alert-danger">
						Sight height is required.  Common heights are 1.5 to 2 inches
					</div>
				</div>
				<div class="form-group" [class.has-error]="zeroRangeYardsControl.invalid && zeroRangeYardsControl.dirty">
					<label class="control-label" title="Range at which scope has been adjusted for point of aim = point of impact">Zero Range (yards)</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<input type="number" name="zeroRangeYards" [(ngModel)]="editedFirearm.zeroRangeYards" #zeroRangeYardsControl="ngModel" [disabled]='isViewOnly' class="form-control" placeholder="Zero Range (yards)" required min="25" max="3000" >
					</div>
					<div [hidden]="isViewOnly || zeroRangeYardsControl.valid || zeroRangeYardsControl.pristine" class="alert alert-danger">
						Zero range is required, so bullet drop can be calculated properly
					</div>
				</div>
				<div class="form-group" [class.has-error]="reticleUnitsControl.invalid && reticleUnitsControl.dirty">
					<label class="control-label" title="Scope crosshair hash mark separation.  Usually Minutes of Angle (MoA), Milliradian (Mil), or Inch Per Hundred Yards (IPHY)">Reticle Units</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<select name="reticleUnits" [(ngModel)]="editedFirearm.reticleUnits" #reticleUnitsControl="ngModel" [disabled]='isViewOnly' class="form-control" required>
							<option value='0'>Mil</option>
							<option value='1'>MoA</option>
							<option value='2'>IPHY</option>
						</select>
					</div>
					<div [hidden]="isViewOnly || reticleUnitsControl.valid || reticleUnitsControl.pristine" class="alert alert-danger">
							Reticle units are required rangeing and hold overs
					</div>
				</div>
				<div class="form-group" [class.has-error]="turretUnitsControl.invalid && turretUnitsControl.dirty">
					<label class="control-label" title="Scope turret hash mark separation.  Usually Minutes of Angle (MoA), Milliradian (Mil), or Inch Per Hundred Yards (IPHY)">Turret Units</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<select name="turretUnits" [(ngModel)]="editedFirearm.turretUnits" #turretUnitsControl="ngModel" [disabled]='isViewOnly' class="form-control" required>
							<option value='0'>Mil</option>
							<option value='1'>MoA</option>
							<option value='2'>IPHY</option>
						</select>
					</div>
					<div [hidden]="isViewOnly || turretUnitsControl.valid || turretUnitsControl.pristine" class="alert alert-danger">
							Turret units are required for rangeing and hold overs
					</div>
				</div>
				<div class="form-group" [class.has-error]="elevationTurretGradientsControl.invalid && elevationTurretGradientsControl.dirty">
					<label class="control-label" title="Number of elevation (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)">Elevation Turret Gradients</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<select name="elevationTurretGradients" [(ngModel)]="editedFirearm.elevationTurretGradients" #elevationTurretGradientsControl="ngModel" [disabled]='isViewOnly' class="form-control" required>
							<option *ngIf='editedFirearm.turretUnits!=0' value='1'>1</option>
							<option *ngIf='editedFirearm.turretUnits!=0' value='2'>2</option>
							<option *ngIf='editedFirearm.turretUnits!=0' value='4'>4</option>
							<option *ngIf='editedFirearm.turretUnits==0' value='10'>10</option>
						</select>
					</div>
					<div [hidden]="isViewOnly || elevationTurretGradientsControl.valid || elevationTurretGradientsControl.pristine" class="alert alert-danger">
							Elevation turret gradients allows values 1,2,4 or 10 (# clicks per turret unti 1,2,4 for MoA and IPHY, and 10 for Mil)
					</div>
				</div>
				<div class="form-group" [class.has-error]="windageTurretGradientsControl.invalid && windageTurretGradientsControl.dirty">
					<label class="control-label" title="Number of windage (up/down) turret clicks per turret unit.  Usually refered to as a fraction (ex: 1/4 MoA = 4 clicks per MoA)">Windage Turret Gradients</label>
					<div class="input-group margin-bottom-sm">
						<span class="input-group-addon"><i class="fa fa-user fa-fw"></i></span>
						<select name="windageTurretGradients" [(ngModel)]="editedFirearm.windageTurretGradients" #windageTurretGradientsControl="ngModel" [disabled]='isViewOnly' class="form-control" required>
							<option *ngIf='editedFirearm.turretUnits!=0' value='1'>1</option>
							<option *ngIf='editedFirearm.turretUnits!=0' value='2'>2</option>
							<option *ngIf='editedFirearm.turretUnits!=0' value='4'>4</option>
							<option *ngIf='editedFirearm.turretUnits==0' value='10'>10</option>
						</select>
					</div>
					<div [hidden]="isViewOnly || windageTurretGradientsControl.valid || windageTurretGradientsControl.pristine" class="alert alert-danger">
							Windage turret gradients allows values 1,2,4 or 10 (# clicks per turret unti 1,2,4 for MoA and IPHY, and 10 for Mil)
					</div>
				</div>
			</form>
		</div>
		<div class="panel-footer">
			<div *ngIf='isViewOnly'>
				<button type="submit" class="btn btn-success" (click)='edit()'><i class="fa fa-check"></i> Edit</button>
			</div>
			<div *ngIf='!isViewOnly'>
				<button type="submit" class="btn btn-success" [disabled]="form.pristine || form.invalid" (click)='save()'><i class="fa fa-check"></i> Save</button>
				<button type="submit" class="btn btn-danger" (click)="cancel()"><i class="fa fa-times"></i> Cancel</button>
			</div>
		</div>
	</div>
</div>
